-- Table: weather.weather_history

-- DROP TABLE weather.weather_history;

CREATE TABLE IF NOT EXISTS weather.weather_history
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    weather_date date,
    weather_value character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT weather_history_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE weather.weather_history
    OWNER to postgres;